seed: 42
num_total_iters: 22000
num_freq: 20
is_clip: !!float '1'
max_length: 256
seed_for_shuffle: 42
batch_size: 512
num_workers: 0
scheduler:
  name: cosine
  params:
    warmup_steps: 2200
    min_lr_ratio: 0.1
optimizer:
  name: AdamW
  params:
    lr: 0.003
    betas:
    - 0.9
    - 0.95
    eps: 0.00000001
    weight_decay: 0.1
layers:
- name: layers.0.self_attn.o_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.0.self_attn.q_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.0.self_attn.k_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.0.self_attn.v_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.0.mlp.gate_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.0.mlp.down_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.0.mlp.up_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.1.self_attn.o_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.1.self_attn.q_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.1.self_attn.k_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.1.self_attn.v_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.1.mlp.gate_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.1.mlp.down_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.1.mlp.up_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.2.self_attn.o_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.2.self_attn.q_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.2.self_attn.k_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.2.self_attn.v_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.2.mlp.gate_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.2.mlp.down_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.2.mlp.up_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.3.self_attn.o_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.3.self_attn.q_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.3.self_attn.k_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.3.self_attn.v_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.3.mlp.gate_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.3.mlp.down_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.3.mlp.up_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.4.self_attn.o_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.4.self_attn.q_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.4.self_attn.k_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.4.self_attn.v_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.4.mlp.gate_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.4.mlp.down_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.4.mlp.up_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.5.self_attn.o_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.5.self_attn.q_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.5.self_attn.k_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.5.self_attn.v_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.5.mlp.gate_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.5.mlp.down_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.5.mlp.up_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.6.self_attn.o_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.6.self_attn.q_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.6.self_attn.k_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.6.self_attn.v_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.6.mlp.gate_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.6.mlp.down_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.6.mlp.up_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.7.self_attn.o_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.7.self_attn.q_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.7.self_attn.k_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.7.self_attn.v_proj
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.15
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.25
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.7.mlp.gate_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.7.mlp.down_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
- name: layers.7.mlp.up_proj
  params:
    alpha_to_rho: 0.0001
    beta_to_rho: 0.001
    rho: 0.000001
    energy: 0.999
    init_energy: 0.35
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.35
    rate_sparsity: 0.03
    is_adaptive: true
    rate_decay: 2
