model_type: GPT
seed: 42
training:
  batch_size: 12
  num_epochs: 6000
  num_workers: 4
  dataloader: train_loader
scheduler:
  name: StepLR
  params:
    step_size: 5
    gamma: 0.85
optimizer:
  name: AdamW
  params:
    lr: 0.0006
    weight_decay: 0.1
    betas:
    - 0.9
    - 0.95
layers:
- name: transformer.wte.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.01
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.wpe.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.01
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.0.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.0.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.0.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.0.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.1.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.1.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.1.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.1.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.2.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.2.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.2.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.2.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.3.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.3.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.3.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.3.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.005
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: true
    rate_rank: 0.15
    rate_sparsity: 0.02
    is_adaptive: true
    rate_decay: 0.9
