model_type: GPT
seed: 42
layers:
  - name: transformer.h.0.attn.c_attn.weight
    params:
      alpha: 0.0001  # Regularization parameter for the layer
      beta: 0.00001  # Sparsity parameter for the layer
      rho: 0.001  # Penalty parameter for the layer
      energy: 0.9  # Energy parameter for the layer
      init_energy: 0.3  # Initial energy for the layer
      iter_max: 1  # Maximum number of iterations for the layer
      tol: 0.001  # Tolerance for convergence
      loss_version: v1  # Version of the loss function, v1: X - L - S -Y/rho, v2: X - L
      is_cal: True  # Whether to calculate the sparse matrix for this layer
  - name: transformer.h.0.attn.c_proj.weight
    params:
      alpha: 0.0001
      beta: 0.00002
      rho: 0.001
      energy: 0.9
      init_energy: 0.3
      iter_max: 1
      tol: 0.001
      loss_version: v1
      is_cal: True

training:
  batch_size: 1
  num_epochs: 100
  num_workers: 4
  dataloader: train_loader  

scheduler:
  name: StepLR
  params:
    step_size: 5
    gamma: 0.7

optimizer:
  name: AdamW
  params:
    lr: 0.008           
    weight_decay: 0.0
    betas: null    
