seed: 42
num_epochs: 6000
model:
  name: GPT
  params:
    n_layer: 12
    n_head: 12
    n_embd: 768
    vocab_size: 50304
    block_size: 1024
dataloader:
  split: train
  batch_size: 12
  num_workers: 4
  block_size: 1024
  steps_per_epoch: 100
  tokens_per_epoch: null
  dataset: openwebtext
scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 598000
    eta_min: 0.00006
optimizer:
  name: SGD
  params:
    lr: 0.0006
layers:
- name: transformer.h.0.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.0.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.0.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.0.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.1.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.1.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.1.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.1.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.2.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.2.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.2.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.2.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.3.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.3.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.3.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.3.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.4.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.4.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.4.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.4.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.5.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.5.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.5.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.5.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.6.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.6.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.6.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.6.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.7.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.7.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.7.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.7.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.8.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.8.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.8.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.8.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.9.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.9.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.9.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.9.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.10.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.10.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.10.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.10.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.11.attn.c_attn.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.11.attn.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.11.mlp.c_fc.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
- name: transformer.h.11.mlp.c_proj.weight
  params:
    alpha_to_rho: 0.01
    beta_to_rho: 0.001
    rho: 0.001
    energy: 0.9
    init_energy: 0.3
    iter_max: 1
    tol: 0.001
    loss_version: v1
    is_cal: false
    rate_rank: 0.15
    rate_sparsity: 0.1
    is_adaptive: true
    rate_decay: 0.9
