universe        = vanilla
executable      = /lustre/home/hma2/projects/awd-LoRA/myenv/bin/python
initialdir      = /lustre/home/hma2/projects/awd-LoRA

log             = jobs_batch/task.log
output          = jobs_batch/task.out
error           = jobs_batch/task.err

request_cpus    = 8
request_memory  = 100000
request_gpus    = 8
requirements = (
    CUDACapability >= 9.0 && \
    CUDACapability < 9.1 && \
    !regexp("GPU-a0e440fb", TARGET.DetectedGPUs) && \
    !regexp("GPU-6afc8b57", TARGET.DetectedGPUs) && \
    !regexp("GPU-00a214e8", TARGET.DetectedGPUs) && \
    !regexp("GPU-9221ffea", TARGET.DetectedGPUs) && \
    !regexp("GPU-448e8d48", TARGET.DetectedGPUs) && \
    !regexp("GPU-6ecb75e1", TARGET.DetectedGPUs) && \
    !regexp("GPU-a3569e05", TARGET.DetectedGPUs) && \
    !regexp("GPU-6f9cd3b3", TARGET.DetectedGPUs) && \
    !regexp("GPU-cebba8d2", TARGET.DetectedGPUs)
)
getenv          = True

queue