universe        = vanilla
executable      = /lustre/home/hma2/projects/awd-LoRA/myenv/bin/python
initialdir      = /lustre/home/hma2/projects/awd-LoRA

log             = jobs_batch/task.log
output          = jobs_batch/task.out
error           = jobs_batch/task.err

request_cpus    = 8
request_memory  = 100000
request_gpus    = 8
requirements = ( \
    CUDACapability >= 9.0 && \
    CUDACapability < 9.1 && \
    !regexp("i101", TARGET.Machine) && \
    !regexp("i102", TARGET.Machine))
getenv          = True

queue