seed: 42
name: vit_b8_vanilla
model_config: vit_b8_model.json
training_mode: vanilla
model_type: dino_vitb8
task: dino_feature_distillation
runtime: cluster
precision: bfloat16
num_total_iters: 120000
num_freq: 20
gradient: coupled
is_asyn: false
is_init: false
is_wandb: true
is_monitor: true
save_interval: 5000
is_clip: !!float '1'
seed_for_shuffle: 42
batch_size: 32
num_workers: 0
data:
  type: vision
  dataset: ILSVRC/imagenet-1k
  location: cluster_snapshot
  root: /lustre/fast/fast/hma2/data/imagenet2012/hf_cache/hub/datasets--ILSVRC--imagenet-1k/snapshots/49e2ee26f3810fb5a7536bbf732a7b07389a47b5
  cache_dir: /lustre/home/hma2/hf/datasets
  split: train
  streaming: true
  shuffle: true
  shuffle_buffer_size: 10000
distillation:
  initialization: random_init
  loss: mse
  global_weight: !!float '1'
  patch_weight: !!float '1'
scheduler:
  name: cosine
  params:
    warmup_steps: 2000
    min_lr_ratio: 0.1
optimizer:
  name: AdamW
  params:
    lr: 0.0001
    betas:
    - 0.9
    - 0.95
    eps: 0.00000001
    weight_decay: !!float '0'
layers: []
