#!/usr/bin/env python3
"""Prepare immutable text shards, or an explicitly marked synthetic fixture."""
from pathlib import Path
import argparse
import json
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from salaad_moe.config import load_config, validate_config
from salaad_moe.data import build_corpus, file_sha256, make_synthetic_corpus


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True)
    parser.add_argument(
        "--output", required=True, help="New directory; existing data is never overwritten"
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument(
        "--input",
        nargs="+",
        help="Local JSONL, JSONL.GZ, JSONL.ZST/JSONL.ZSTD, or Parquet shards",
    )
    source.add_argument("--shard-manifest", help="shards.json generated by fetch_moe_sources.py")
    source.add_argument("--synthetic-smoke", action="store_true")
    parser.add_argument("--synthetic-sequences", type=int, default=128)
    parser.add_argument(
        "--tokenizer-json", help="Optional local tokenizer JSON; its content hash is recorded"
    )
    parser.add_argument("--text-key", default="text")
    parser.add_argument(
        "--max-train-tokens", type=int,
        help="Cap training prediction tokens at a multiple of seq_length; still fill held-out splits",
    )
    parser.add_argument(
        "--write-megatron-indexed",
        action="store_true",
        help="Also emit split .bin/.idx; pinned Megatron must be on PYTHONPATH",
    )
    args = parser.parse_args()
    config = load_config(args.config)
    validate_config(config)
    if args.synthetic_smoke:
        if args.max_train_tokens is not None:
            parser.error("--max-train-tokens applies to text shards; use --synthetic-sequences for smoke data")
        if args.write_megatron_indexed:
            parser.error("Use text shards for the formal Megatron indexed-data route")
        manifest = make_synthetic_corpus(config, args.output, args.synthetic_sequences)
    else:
        inputs = args.input
        if args.shard_manifest:
            source_info = json.loads(Path(args.shard_manifest).read_text())
            if (
                source_info["dataset"] != config["data"]["dataset"]
                or source_info["revision"] != config["data"]["dataset_revision"]
            ):
                raise ValueError("Shard manifest differs from the pinned dataset")
            for entry in source_info["ordered_shards"]:
                if file_sha256(entry["local_path"]) != entry["sha256"]:
                    raise ValueError(f"Downloaded source shard changed: {entry['local_path']}")
            inputs = [entry["local_path"] for entry in source_info["ordered_shards"]]
        manifest = build_corpus(
            config,
            inputs,
            args.output,
            args.tokenizer_json,
            args.text_key,
            args.write_megatron_indexed,
            max_train_tokens=args.max_train_tokens,
        )
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
