executable      = /lustre/home/hma2/projects/awd-LoRA/myenv/bin/python
arguments       = \
    -u -m torch.distributed.run \
    --nproc_per_node=5 \
    --nnodes=1 \
    --rdzv_backend=c10d \
    --rdzv_endpoint=127.0.0.1:29500 \
    LowSpa/train_normal.py

initialdir      = /lustre/home/hma2/projects/awd-LoRA

log             = jobs_normal/task$(Process).log
error           = jobs_normal/task$(Process).err
output          = jobs_normal/task$(Process).out

request_cpus    = 5
request_memory  = 65536
request_gpus    = 5

queue 1