executable      = /lustre/home/hma2/projects/awd-LoRA/myenv/bin/python
arguments       = \
    -u -m torch.distributed.run \
    --nproc_per_node=5 \
    --nnodes=1 \
    --rdzv_backend=c10d \
    --rdzv_endpoint=127.0.0.1:29500 \
    scripts/train_salad.py --alpha_rate $(arg1) --beta_rate $(arg2)

initialdir      = /lustre/home/hma2/projects/awd-LoRA

log             = jobs_batch/task$(Process).log
error           = jobs_batch/task$(Process).err
output          = jobs_batch/task$(Process).out

request_cpus    = 5
request_memory  = 100000
request_gpus    = 5
requirements = (CUDACapability >= 8.0 && CUDACapability < 9.0) 

getenv          = True

queue arg1 arg2 from batch_params.txt