executable = /lustre/home/hma2/projects/awd-LoRA/myenv/bin/python

arguments = \
    -u -m torch.distributed.run \
    --nproc_per_node=4 \
    --nnodes=1 \
    --rdzv_backend=c10d \
    --rdzv_endpoint=127.0.0.1:29504 \
    scripts/train_salad.py \
    --cfg_version llama_consensus_60m_loop1_block6

initialdir = /lustre/home/hma2/projects/awd-LoRA

log = jobs/consensus_salaad_loop1_block6_$(Cluster)_$(Process).log
error = jobs/consensus_salaad_loop1_block6_$(Cluster)_$(Process).err
output = jobs/consensus_salaad_loop1_block6_$(Cluster)_$(Process).out

request_cpus = 4
request_memory = 100000
request_gpus = 4

requirements = ( \
    CUDACapability >= 9.0 && \
    CUDACapability < 9.1 && \
    !regexp("GPU-4c275e72", TARGET.DetectedGPUs) && \
    !regexp("GPU-a0e440fb", TARGET.DetectedGPUs) && \
    !regexp("GPU-b50eee5a", TARGET.DetectedGPUs) && \
    !regexp("GPU-57cf3c62", TARGET.DetectedGPUs) && \
    !regexp("GPU-b65aba4e", TARGET.DetectedGPUs) && \
    !regexp("GPU-90f1a7d5", TARGET.DetectedGPUs) && \
    !regexp("GPU-2d57d3d7", TARGET.DetectedGPUs) && \
    !regexp("GPU-1feef0b3", TARGET.DetectedGPUs) \
)

getenv = True

queue 1
