executable      = /lustre/home/hma2/projects/awd-LoRA/myenv/bin/python
arguments       = \
    -u -m torch.distributed.run \
    --nproc_per_node=2 \
    --nnodes=1 \
    --rdzv_backend=c10d \
    --rdzv_endpoint=127.0.0.1:29500 \
    scripts/rate_distortion_estimator.py

initialdir      = /lustre/home/hma2/projects/awd-LoRA

log             = jobs_eval2/task$(Process).log
error           = jobs_eval2/task$(Process).err
output          = jobs_eval2/task$(Process).out

request_cpus    = 2
request_memory  = 100000
request_gpus    = 2
requirements = (CUDACapability >= 8.9 && CUDACapability < 9.1) 

getenv          = True

queue 1