executable      = /lustre/home/hma2/projects/awd-LoRA/myenv/bin/python
arguments       = \
    -u -m torch.distributed.run \
    --nproc_per_node=1 \
    --nnodes=1 \
    --rdzv_backend=c10d \
    --rdzv_endpoint=127.0.0.1:29500 \
    scripts/read_rcpa_X.py

initialdir      = /lustre/home/hma2/projects/awd-LoRA

log             = jobs_recover/task$(Process).log
error           = jobs_recover/task$(Process).err
output          = jobs_recover/task$(Process).out

request_cpus    = 1
request_memory  = 60000
request_gpus    = 1
requirements = (CUDACapability >= 8.0 && CUDACapability < 9.1) 

getenv          = True

queue 1