executable      = /lustre/home/hma2/projects/awd-LoRA/myenv/bin/python
arguments       = \
    -u -m torch.distributed.run \
    --nproc_per_node=5 \
    --nnodes=1 \
    --rdzv_backend=c10d \
    --rdzv_endpoint=127.0.0.1:29500 \
    analysis/LS_recover.py

initialdir      = /lustre/home/hma2/projects/awd-LoRA

log             = jobs_recover/task$(Process).log
error           = jobs_recover/task$(Process).err
output          = jobs_recover/task$(Process).out

request_cpus    = 5
request_memory  = 100000
request_gpus    = 5
requirements = (CUDACapability >= 8.9 && CUDACapability < 9.1) 

getenv          = True

queue 1