executable      = /lustre/home/hma2/projects/awd-LoRA/myenv/bin/python
arguments       = \
    -u -m torch.distributed.run \
    --nproc_per_node=1 \
    --nnodes=1 \
    --rdzv_backend=c10d \
    --rdzv_endpoint=127.0.0.1:29500 \
    scripts/resave_model.py

initialdir      = /lustre/home/hma2/projects/awd-LoRA

log             = jobs_eval/task$(Process).log
error           = jobs_eval/task$(Process).err
output          = jobs_eval/task$(Process).out

request_cpus    = 1
request_memory  = 100000
request_gpus    = 1
requirements = ( \
    CUDACapability >= 9.0 && \
    CUDACapability < 9.1 && \
    !regexp("GPU-4c275e72", TARGET.DetectedGPUs) && \
    !regexp("GPU-a0e440fb", TARGET.DetectedGPUs) && \
    !regexp("GPU-b50eee5a", TARGET.DetectedGPUs) && \
    !regexp("GPU-57cf3c62", TARGET.DetectedGPUs) && \
    !regexp("GPU-b65aba4e", TARGET.DetectedGPUs) && \
    !regexp("GPU-90f1a7d5", TARGET.DetectedGPUs) && \
    !regexp("GPU-2d57d3d7", TARGET.DetectedGPUs) && \
    !regexp("GPU-1feef0b3", TARGET.DetectedGPUs) \
)

getenv          = True

queue 1