executable      = /lustre/home/hma2/projects/awd-LoRA/myenv/bin/python
arguments       = \
    -u -m torch.distributed.run \
    --standalone \
    --nproc_per_node=4 \
    --nnodes=1 \
    scripts/train_salad.py \
    --cfg_version vit_b8_shallow_qkv_r35_s35 \
    --folder salaad_vision

initialdir      = /lustre/home/hma2/projects/awd-LoRA

log             = jobs/salaad_vision_shallow_qkv_r35_s35_$(Cluster)_$(Process).log
error           = jobs/salaad_vision_shallow_qkv_r35_s35_$(Cluster)_$(Process).err
output          = jobs/salaad_vision_shallow_qkv_r35_s35_$(Cluster)_$(Process).out

request_cpus    = 12
request_memory  = 64000
request_gpus    = 4

requirements = ( \
    CUDACapability >= 9.0 && \
    CUDACapability < 9.1 && \
    TARGET.Machine != "i205.internal.cluster.is.localnet" && \
    !regexp("GPU-a82810cc", TARGET.DetectedGPUs) && \
    !regexp("GPU-1f35d697", TARGET.DetectedGPUs) && \
    !regexp("GPU-45d24b88", TARGET.DetectedGPUs) && \
    !regexp("GPU-0e5a23fb", TARGET.DetectedGPUs) \
)

getenv          = True
environment     = "PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True"

queue 1
