executable      = /bin/bash
arguments       = scripts/generate_mixed_rho_attention_heatmaps.sh

initialdir      = /lustre/home/hma2/projects/awd-LoRA

log             = jobs/salaad_vision_mixed_rho_attention_heatmaps_$(Cluster)_$(Process).log
error           = jobs/salaad_vision_mixed_rho_attention_heatmaps_$(Cluster)_$(Process).err
output          = jobs/salaad_vision_mixed_rho_attention_heatmaps_$(Cluster)_$(Process).out

request_cpus    = 4
request_memory  = 32000
request_gpus    = 1

requirements = (CUDACapability >= 8.0)

getenv          = True

queue 1
