executable      = /lustre/home/hma2/projects/awd-LoRA/myenv/bin/python
arguments       = \
    -u -m torch.distributed.run \
    --nproc_per_node=8 \
    --nnodes=1 \
    --rdzv_backend=c10d \
    --rdzv_endpoint=127.0.0.1:29500 \
    scripts/train_salad.py

initialdir      = /lustre/home/hma2/projects/awd-LoRA

log             = jobs2/task$(Process).log
error           = jobs2/task$(Process).err
output          = jobs2/task$(Process).out

request_cpus    = 8
request_memory  = 100000
request_gpus    = 8
requirements = ( \
    CUDACapability >= 9.0 && \
    CUDACapability < 9.1 && \
    !regexp("GPU-6df712bd", TARGET.DetectedGPUs) && \
    !regexp("GPU-1aaa8614", TARGET.DetectedGPUs) && \
    !regexp("GPU-029c1a33", TARGET.DetectedGPUs) && \
    !regexp("GPU-2851f610", TARGET.DetectedGPUs) && \
    !regexp("GPU-d225c007", TARGET.DetectedGPUs) && \
    !regexp("GPU-9606ef1c", TARGET.DetectedGPUs) && \
    !regexp("GPU-b2aa3b92", TARGET.DetectedGPUs) && \
    !regexp("GPU-6614f0ce", TARGET.DetectedGPUs) )

getenv          = True

queue 1