executable      = /lustre/home/hma2/projects/awd-LoRA/myenv/bin/python
arguments       = \
    -u -m torch.distributed.run \
    --nproc_per_node=2 \
    --nnodes=1 \
    --rdzv_backend=c10d \
    --rdzv_endpoint=127.0.0.1:29500 \
    scripts/train_salad.py

initialdir      = /lustre/home/hma2/projects/awd-LoRA

log             = jobs/task$(Process).log
error           = jobs/task$(Process).err
output          = jobs/task$(Process).out

request_cpus    = 2
request_memory  = 65536
request_gpus    = 2

queue 1